export const CHANGE_HOMELESS = 'CHANGE_HOMELESS'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const CHANGE_VULNERABILITY = 'CHANGE_VULNERABILITY'
export const CHANGE_INTENTION = 'CHANGE_INTENTION'
